In [ ]:
import numpy as np

### Practice some NumPy commands:
- Create 3 * 3 array.
- Check its shape.
- Select first row.
- Select 2nd column.
- Select the 2nd element in the third column.
- Create 2*2 from the first two elements of the first 2 rows and columns.
- Create single row vector.
- Create single column vector.

In [ ]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
array.shape

(3, 3)

In [ ]:
array[0]

array([1, 2, 3])

In [ ]:
array[:,1]

array([2, 5, 8])

In [ ]:
array[:,2][1]

6

In [ ]:
sub_array = array[:2,:2]

In [ ]:
sub_array

array([[1, 2],
       [4, 5]])

In [ ]:
row_vector = np.array([1,2,3,4])

In [ ]:
row_vector

array([1, 2, 3, 4])

In [ ]:
col_vector = np.array([[1],[2],[3]])

In [ ]:
col_vector

array([[1],
       [2],
       [3]])

## Represent in paper and as numpy arrays Ax=b
![image.png](attachment:image.png)

In [ ]:
A = np.array([[3, -1], [1, 0]])
b = np.array([[2], [4]])

In [ ]:
X = np.linalg.inv(A) @ b

In [ ]:
X

array([[ 4.],
       [10.]])

In [ ]:
A = np.array([[3, -2], [2, -2]])
b = np.array([[7], [2]])

In [ ]:
X = np.linalg.inv(A) @ b
X

array([[5.],
       [4.]])

In [ ]:
A = np.array([[3, -2, 1], [1, 1, 1], [3, -2, -1]])
b = np.array([[7], [2], [3]])

In [ ]:
X = np.linalg.inv(A) @ b
X

array([[ 1.],
       [-1.],
       [ 2.]])

### Using numpy arrays
- Multiply matrix <b>A</b> and vector <b>x</b> and make sure the result is <b>b</b> from the above exercise.

In [ ]:
b

array([[7],
       [2],
       [3]])

In [ ]:
A @ X

array([[7.],
       [2.],
       [3.]])

## Calculate in paper then confirm your results using numpy linalg.norm().
![image.png](attachment:image.png)

In [ ]:
from numpy.linalg import norm
from numpy import inf

array1 = np.array([1,2,3])
array2 = np.array([3,3,1,3])
array3 = np.array([2,3,4])

In [ ]:
norm1 = norm(array1, 1)
norm2 = norm(array1, 2)
norm_max = norm(array1, inf)

In [ ]:
print(norm1)
print(norm2)
print(norm_max)

6.0
3.7416573867739413
3.0


In [ ]:
norm3 = norm(array3, 3)
norm3

4.626065009182741

## Calculate in paper then confirm your results using numpy.
### Calculate L1, L2, L3, and Lmax for the following vectors:
### [5,6], [4,3,2], [4,3,2,8,9].

In [ ]:
array1 = np.array([5,6])
array2 = np.array([4,3,2])
array3 = np.array([4,3,2,8,9])

In [ ]:
norm1 = norm(array1, 1)
norm2 = norm(array1, 2)
norm3 = norm(array3, 3)
norm_max = norm(array1, inf)

In [ ]:
print(norm1)
print(norm2)
print(norm3)
print(norm_max)

11.0
7.810249675906654
11.02473771449733
6.0


## Calculate in paper then confirm your results using numpy.
![image.png](attachment:image.png)

In [ ]:
arr1 = np.array([2, -1, 5, 0])
arr2 = np.array([4, -3, 1, -1])

In [ ]:
res = arr1 @ arr2
res

16

In [ ]:
arr1 = np.array([3, 2, -1, 4])
arr2 = np.array([1, -1, 1, 0])

In [ ]:
# (3*1) + (2*-1) + (-1 * 1) + (4 * 0) = 3 - 2 -1 + 0 = 0

In [ ]:
arr1 @ arr2

0

## Calculate in paper then confirm your results using numpy.
### Create two vectors in 2, 3, and 4 dimensions.
### Perform vector addition, subtraction, and dot product of these vectors.

In [ ]:
arr1 = np.array([1,2])
arr2 = np.array([3,5])

In [ ]:
print(arr1 + arr2)    # 1+3, 2+5
print(arr1 @ arr2)    # (1*3) + (2*5) = 13
print(arr1 - arr2)    # 1-3, 2-5

[4 7]
13
[-2 -3]


In [ ]:
print(arr1 + arr2)    # 1+3, 2+5
print(arr1 @ arr2)    # (1*3) + (2*5) = 13
print(arr1 - arr2)    # 1-3, 2-5

[4 7]
13
[-2 -3]


In [ ]:
arr1 = np.array([2, -1, 5, 0])
arr2 = np.array([4, -3, 1, -1])

In [ ]:
print(arr1 + arr2)    # 2+4, -1-3, 5+1, 0-1
print(arr1 @ arr2)    # (2*4) + (-1*-3) + (5*1) + (0 * -1) = 16
print(arr1 - arr2)    # 2-4, -1+3, 5-1, 0+1

[ 6 -4  6 -1]
16
[-2  2  4  1]


## Calculate in paper then confirm your results using numpy.
![image.png](attachment:image.png)

## Different Types of Matrices
#### Create 3 by 3 and 4 by 4 identity matrices 

In [ ]:
A = np.array([[3, 1, 0], [2, 1, 2]])
B = np.array([[1,3], [2, 5], [-1, 3]])
C = A @ B
C

array([[ 5, 14],
       [ 2, 17]])

In [ ]:
C.T

array([[ 5,  2],
       [14, 17]])

#### Create a diagonal matrix contains [2,4,5,11] numbers in it's diagonal.

In [ ]:
v = np.array([2, 4, 5, 11])
np.diag(v)

array([[ 2,  0,  0,  0],
       [ 0,  4,  0,  0],
       [ 0,  0,  5,  0],
       [ 0,  0,  0, 11]])

#### Create a 5 by 5 scalar matrix of number 7

In [ ]:
np.eye(3)*7

array([[7., 0., 0.],
       [0., 7., 0.],
       [0., 0., 7.]])

#### Using SymPy get the rref of the following matrices

In [ ]:
from sympy import *

In [ ]:
arr = Matrix([[1,0,1,3],[2,3,4,7],[-1,-3,-3,-4]])

In [ ]:
arr.rref()

(Matrix([
 [1, 0,   1,   3],
 [0, 1, 2/3, 1/3],
 [0, 0,   0,   0]]),
 (0, 1))

#### Find the solution of the following system of linear equation using SymPy Matrix rref()

![image-2.png](attachment:image-2.png)
![image-3.png](attachment:image-3.png)

#### Find the solution of the following system of linear equation 
- By hand (Paper and pen)
- Confirm your answer using SymPy Matrix rref()

![image.png](attachment:image.png)
![image-2.png](attachment:image-2.png)
![image-3.png](attachment:image-3.png)
![image-5.png](attachment:image-5.png)